"""Backtest runner: reproduce the forecasting process as if it had really
run once per day through the test period, per the case statement:

    "на 31 января - сформировать прогноз на следующие 24-48 часов;
     на 1 февраля - сформировать новый прогноз на следующие 24-48 часов;
     далее последовательно повторить ... в течение тестового периода."

Usage (from project root):
    python scripts/run_backtest.py

For each turbine, issues one agentic cycle (src/agent/orchestrator.py) per
day from 2026-01-31 to 2026-02-27 inclusive (28 issues -- the last day
whose lead=24h/48h outputs still land inside the Feb-2026 test period).
Each cycle uses ONLY previous-runs archived weather (fixed lead time,
verified fully populated for this window in
outputs/weather/weather_client_check.md) -- never live/actual weather.

Writes, per turbine:
  - outputs/forecasts/turbine_<id>_all_issues.csv   (every issue's every hour)
  - outputs/forecasts/turbine_<id>_final.csv          (one row per target hour,
    Feb 1-28 2026, keeping the freshest -- smallest lead_hours -- estimate)
  - outputs/run_logs/turbine_<id>_<issue_date>_lead<H>.json (per-cycle QA log)
  - outputs/forecasts/backtest_report.md (combined summary + revision analysis)
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import pandas as pd

from src import config
from src.agent import orchestrator, schema as agent_schema
from src.data import schema as data_schema
from src.features import engineering
from src.features.build import load_turbine_hourly
from src.models import train

ISSUE_DATES = pd.date_range("2026-01-31", "2026-02-27", freq="D").strftime("%Y-%m-%d").tolist()
TEST_PERIOD_START = "2026-02-01"
TEST_PERIOD_END_EXCLUSIVE = "2026-03-01"  # i.e. includes all 24 hours of 2026-02-28


def run_turbine_backtest(turbine_id: int) -> dict:
    turbine = config.load_turbines()[turbine_id]
    trained = train.load_trained_model(turbine_id)
    hourly = load_turbine_hourly(turbine_id)
    power_clean = engineering.clean_power_series(hourly)

    verdict_counts = {}
    n_retried = 0
    n_failed = 0

    for issue_date in ISSUE_DATES:
        results = orchestrator.run_forecast_cycle(turbine, issue_date, trained, power_clean, mode="backtest")
        for lead_hours, r in results.items():
            verdict_counts[r["verdict"]] = verdict_counts.get(r["verdict"], 0) + 1
            if r["n_fetch_attempts"] > 1:
                n_retried += 1
            if r["verdict"] == "failed_weather_fetch":
                n_failed += 1

    all_issues_path = agent_schema.FORECASTS_DIR / f"turbine_{turbine_id}_all_issues.csv"
    all_issues = pd.read_csv(all_issues_path, parse_dates=["valid_time"])

    in_test_period = all_issues[
        (all_issues["valid_time"] >= TEST_PERIOD_START) & (all_issues["valid_time"] < TEST_PERIOD_END_EXCLUSIVE)
    ].copy()
    final = in_test_period.sort_values("lead_hours").drop_duplicates(subset="valid_time", keep="first")
    final = final.sort_values("valid_time")[["valid_time", "lead_hours", "predicted_power"]]
    final_path = agent_schema.FORECASTS_DIR / f"turbine_{turbine_id}_final.csv"
    final.to_csv(final_path, index=False)

    # Revision analysis: for hours where BOTH a lead=48 (issued 2 days out)
    # and a lead=24 (issued 1 day out, fresher weather) prediction exist,
    # how much did the forecast change? This is the concrete evidence of
    # "recompute when input data updates" -- the later cycle used weather
    # data that did not exist yet when the earlier one ran.
    pivot = in_test_period.pivot_table(index="valid_time", columns="lead_hours", values="predicted_power")
    revision = None
    if 24 in pivot.columns and 48 in pivot.columns:
        both = pivot.dropna(subset=[24, 48])
        if len(both):
            diff = (both[24] - both[48]).abs()
            revision = {"n_hours_with_both": len(both), "mean_abs_revision": float(diff.mean()), "max_abs_revision": float(diff.max())}

    return {
        "turbine_id": turbine_id,
        "n_issues": len(ISSUE_DATES),
        "verdict_counts": verdict_counts,
        "n_cycles_retried": n_retried,
        "n_cycles_failed": n_failed,
        "n_final_hours": len(final),
        "final_coverage_pct": 100 * len(final) / (24 * 28),
        "revision": revision,
        "final_path": str(final_path),
        "all_issues_path": str(all_issues_path),
    }


def write_report(all_results: list[dict]) -> None:
    lines = [
        "# Backtest report",
        "",
        "Generated by `scripts/run_backtest.py`.",
        "",
        f"Issue dates simulated: {ISSUE_DATES[0]} .. {ISSUE_DATES[-1]} ({len(ISSUE_DATES)} daily cycles per turbine).",
        f"Test period covered: {TEST_PERIOD_START} .. 2026-02-28 (hourly, inclusive).",
        "Weather source: previous-runs API only (fixed 24h/48h lead, archived forecasts) -- verified fully "
        "populated for this window in `outputs/weather/weather_client_check.md`; never live/actual weather.",
        "",
    ]

    for res in all_results:
        lines += [
            f"## Turbine {res['turbine_id']}",
            "",
            f"- Cycles run: {res['n_issues']} issue days x 2 lead groups = {res['n_issues'] * 2}",
            f"- Verdicts: {res['verdict_counts']}",
            f"- Cycles that needed a weather-fetch retry: {res['n_cycles_retried']}",
            f"- Cycles that failed even after retries: {res['n_cycles_failed']}",
            f"- Final Feb-2026 forecast coverage: {res['n_final_hours']}/{24*28} hours ({res['final_coverage_pct']:.1f}%)",
            f"- Final forecast: `{res['final_path']}`",
            f"- All-issues detail: `{res['all_issues_path']}`",
        ]
        if res["revision"]:
            rev = res["revision"]
            lines.append(
                f"- Recompute-on-update evidence: for {rev['n_hours_with_both']} hours forecast twice "
                f"(once at lead=48h, again at lead=24h with fresher weather), the mean absolute revision "
                f"was {rev['mean_abs_revision']:.4f} (max {rev['max_abs_revision']:.4f}) normalized power -- "
                f"the agent materially changes its forecast as newer weather data becomes available."
            )
        lines.append("")

    agent_schema.BACKTEST_REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Report written to {agent_schema.BACKTEST_REPORT_PATH}")


def main() -> None:
    all_results = []
    for turbine_id in data_schema.RAW_FILES:
        print(f"\n=== Backtesting turbine {turbine_id}: {len(ISSUE_DATES)} issue days ===")
        res = run_turbine_backtest(turbine_id)
        all_results.append(res)
        print(f"  verdicts={res['verdict_counts']} retried={res['n_cycles_retried']} failed={res['n_cycles_failed']}")
        print(f"  final coverage: {res['n_final_hours']}/{24*28} hours ({res['final_coverage_pct']:.1f}%)")
        if res["revision"]:
            print(f"  mean |lead24 - lead48| revision: {res['revision']['mean_abs_revision']:.4f}")

    write_report(all_results)


if __name__ == "__main__":
    main()
