"""Verification / demo run for the weather client (src/weather/client.py).

Usage (from project root):
    python scripts/run_weather_client_check.py

For each turbine, this proves out the three data sources the plan relies
on (see PLAN_AND_ARCHITECTURE.md section 4.0/6):

  1. previous-runs (fixed 24h/48h lead archived forecast) is fully
     populated over the mandatory backtest window (2026-01-31..2026-02-28)
     -- the zero-leakage source for the backtest.
  2. the actual previous-runs coverage-start date is measured (not
     assumed) for these coordinates.
  3. the ERA5 reanalysis proxy source works for the pre-coverage training
     slice (2023-03-11..coverage start).
  4. the live forecast endpoint works, for production/real-time use.
  5. the disk cache makes a repeated call near-instant.

It writes a summary to outputs/weather/weather_client_check.md and does
not yet assemble the full training feature table (that is the next
roadmap step: joining this weather data with the resampled hourly
turbine data from data/processed/).
"""

import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src import config
from src.weather import client, schema

BACKTEST_START = "2026-01-31"
BACKTEST_END = "2026-02-28"
HISTORY_START = "2023-03-11"

OUTPUT_DIR = schema.PROJECT_ROOT / "outputs" / "weather"


def check_turbine(turbine: config.TurbineInfo) -> list[str]:
    lines = [f"## {turbine.name} (lat={turbine.latitude}, lon={turbine.longitude})", ""]

    # 1. Backtest-window previous-runs coverage.
    backtest_df = client.fetch_previous_runs(turbine.latitude, turbine.longitude, BACKTEST_START, BACKTEST_END)
    n_total = len(backtest_df)
    n_missing = int(backtest_df["value"].isna().sum())
    lines.append(
        f"- **Backtest window** ({BACKTEST_START} -> {BACKTEST_END}) previous-runs: "
        f"{n_total} rows, {n_missing} missing ({100 * n_missing / n_total:.2f}%)."
    )
    for lead in schema.PREVIOUS_RUNS_LEAD_DAYS:
        lead_hours = lead * 24
        sub = backtest_df[(backtest_df["variable"] == "wind_speed_10m") & (backtest_df["lead_hours"] == lead_hours)]
        lines.append(
            f"  - wind_speed_10m @ lead {lead_hours}h: n={len(sub)}, "
            f"missing={int(sub['value'].isna().sum())}, "
            f"range=[{sub['value'].min():.2f}, {sub['value'].max():.2f}] m/s"
        )

    # 2. Measured coverage-start date.
    coverage_start = client.find_previous_runs_coverage_start(
        turbine.latitude, turbine.longitude, search_start="2015-01-01", search_end="2026-01-01"
    )
    lines.append(f"- **Measured previous-runs coverage start** (wind_speed_10m, 24h lead): {coverage_start}")

    # 3. ERA5 reanalysis proxy for the pre-coverage training slice.
    proxy_end = coverage_start or HISTORY_START
    era5_df = client.fetch_historical_weather(turbine.latitude, turbine.longitude, HISTORY_START, proxy_end)
    n_era5 = len(era5_df)
    n_era5_missing = int(era5_df["value"].isna().sum())
    lines.append(
        f"- **Reanalysis proxy** ({HISTORY_START} -> {proxy_end}) for pre-coverage training rows: "
        f"{n_era5} rows, {n_era5_missing} missing."
    )

    # 4. Live forecast.
    live_df = client.fetch_live_forecast(turbine.latitude, turbine.longitude, forecast_days=2)
    n_live = len(live_df)
    n_live_missing = int(live_df["value"].isna().sum())
    lines.append(f"- **Live forecast** (next 2 days, as of run time): {n_live} rows, {n_live_missing} missing.")

    # 5. Cache effectiveness: repeat the backtest call, timed.
    t0 = time.perf_counter()
    client.fetch_previous_runs(turbine.latitude, turbine.longitude, BACKTEST_START, BACKTEST_END)
    elapsed_cached = time.perf_counter() - t0
    lines.append(f"- Repeated backtest fetch (cache hit): {elapsed_cached * 1000:.1f} ms.")
    lines.append("")
    return lines


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    turbines = config.load_turbines()

    report = ["# Weather client verification", "", "Generated by `scripts/run_weather_client_check.py`.", ""]
    for turbine in turbines.values():
        print(f"=== {turbine.name} ===")
        lines = check_turbine(turbine)
        for line in lines:
            print(line)
        report += lines

    report_path = OUTPUT_DIR / "weather_client_check.md"
    report_path.write_text("\n".join(report), encoding="utf-8")
    print(f"Report written to {report_path}")


if __name__ == "__main__":
    main()
