"""Model training entry point.

Usage (from project root):
    python scripts/train_models.py

For each turbine, trains one LightGBM regressor on the assembled training
table (data/processed/turbine_<id>_train.parquet), using both lead-time
groups with `lead_hours` as a feature. Evaluated on a held-out January
2026 slice against two baselines (persistence, empirical power curve).
The shipped model is a separate refit on all data (see src/models/train.py
docstring for why). Writes:
  - outputs/models/turbine_<id>_lgbm.txt  (LightGBM native model file)
  - outputs/models/model_report.md
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.data import schema as data_schema
from src.models import schema, train


MODEL_DISPLAY_NAMES = {
    "lgbm": "power_curve + lgbm_residual",
    "power_curve_baseline": "power_curve_baseline",
    "persistence_baseline": "persistence_baseline",
}


def write_report(all_results: list[dict]) -> None:
    lines = ["# Model training report", "", "Generated by `scripts/train_models.py`.", ""]
    lines.append(
        f"Time-based split: train < `{schema.VALID_START}` "
        f"(early-stopping dev set from `{schema.EARLY_STOP_START}`), validation = January 2026."
    )
    lines.append("")

    for res in all_results:
        tid = res["turbine_id"]
        lines += [
            f"## Turbine {tid}",
            "",
            f"- Dropped {res['n_dropped_proxy']:,} `reanalysis_proxy` rows before training "
            "(ablation showed the mixed regime hurts -- see PLAN_AND_ARCHITECTURE.md 5.2).",
            f"- Reporting fit: {res['n_train_fit']:,} rows (train) / {res['n_train_earlystop']:,} rows (early-stopping dev). "
            "Metrics below are from THIS model, which never saw the dev set or January 2026.",
            f"- Shipped/production model: refit on all {res['n_production_rows']:,} previous_runs rows through "
            f"validation's end, with n_estimators fixed to the reporting fit's best_iteration_ "
            f"({res['production_n_estimators']}) -- not the model the table below measures, but expected to be "
            "at least as good on truly unseen data since it strictly has more, more-recent information.",
            f"- Model saved to `{res['model_path']}`",
            "",
            "| lead_hours | n_valid | model | MAE | RMSE | R2 |",
            "|---|---|---|---|---|---|",
        ]
        for lead_hours, by_lead in res["by_lead"].items():
            for model_name in ("lgbm", "power_curve_baseline", "persistence_baseline"):
                m = by_lead[model_name]
                lines.append(
                    f"| {lead_hours} | {by_lead['n_valid']:,} | {MODEL_DISPLAY_NAMES[model_name]} | "
                    f"{m['mae']:.4f} | {m['rmse']:.4f} | {m['r2']:.4f} |"
                )
        lines.append("")

        top_features = list(res["feature_importance"].items())[:8]
        lines.append(
            "Top residual-model feature importances (gain): "
            + ", ".join(f"{k}={v:.0f}" for k, v in top_features)
        )
        lines.append("")

    report_path = schema.MODELS_OUTPUT_DIR / "model_report.md"
    report_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Report written to {report_path}")


def main() -> None:
    schema.MODELS_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    all_results = []
    for turbine_id in data_schema.RAW_FILES:
        print(f"\n=== Training turbine {turbine_id} ===")
        results = train.train_and_evaluate_turbine(turbine_id)
        all_results.append(results)
        for lead_hours, by_lead in results["by_lead"].items():
            print(f"  lead={lead_hours}h (n={by_lead['n_valid']}):")
            for model_name in ("lgbm", "power_curve_baseline", "persistence_baseline"):
                m = by_lead[model_name]
                print(f"    {MODEL_DISPLAY_NAMES[model_name]:28s} MAE={m['mae']:.4f} RMSE={m['rmse']:.4f} R2={m['r2']:.4f}")

    write_report(all_results)


if __name__ == "__main__":
    main()
